name: Install and Configure Poetry 
description: Installs and configures poetry.
inputs:
  poetry-version:
    description: The version of poetry to install
    required: false
    default: "1.4.1"
  private-package-repo-url:
    description: The url of the private package repository you want to add to poetry. You must also specify `private-package-repo-username`
    required: false
    default: ""
  private-package-repo-username:
    description: The username for the private package repository you want to add to poetry
    required: false
    default: ""
  private-package-repo-password:
    description: The password for the private package repository you want to add to poetry
    required: false
    default: ""
  working-directory:
    description: The working directory where this action should run. Defaults to the root of the git repository.
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Install and Configure Poetry
      shell: bash
      working-directory: "${{inputs.working-directory}}"
      run: |
        python -m pip install --upgrade pip
        pip install poetry==${{inputs.poetry-version}} --upgrade
        poetry config virtualenvs.in-project true
        if [ -n "${{inputs.private-package-repo-url}}" ]; then
          if [ -z "${{inputs.private-package-repo-username}}" ]; then
            echo "private-package-repo-username is required when private-package-repo-url is provided" 1>&2
            exit 1
          fi

          poetry config repositories.private "${{ inputs.private-package-repo-url }}"
          poetry config http-basic.private "${{ inputs.private-package-repo-username }}" "${{ inputs.private-package-repo-password }}"
        fi
