name: Install Dependencies with Gemfury
description: Installs dependencies with Triax's Gemfury registry

runs:
  using: composite
  steps:
    - name: Authenticate Gemfury
      run: echo "//npm-proxy.fury.io/triaxtec/:_authToken=$GEMFURY_PULL_TOKEN" > .npmrc
      env:
        GEMFURY_PULL_TOKEN: ${{ secrets.GEMFURY_PULL_TOKEN }}

    - run: npm config set registry https://npm-proxy.fury.io/triaxtec/

    - name: Install Dependencies
      run: "npm ci"
