name: Install Dependencies with Authenticated Registry
description: Installs dependencies with an NPM registry
inputs:
  npm-registry-url:
    description: The protocol relative (without http/s) NPM registry url
    required: true
    default: NOT_SPECIFIED
  npm-registry-pull-token:
    description: The token used to authenticate with the NPM registry
    required: true
    default: NOT_SPECIFIED

runs:
  using: composite
  steps:
    - name: Authenticate NPM Registry
      shell: bash
      run: echo "//${{inputs.npm-registry-url}}/:_authToken=${{inputs.npm-registry-pull-token}}" > .npmrc

    - run: npm config set registry https://${{inputs.npm-registry-url}}/
      shell: bash

    - name: Install Dependencies
      shell: bash
      run: "npm ci"
