name: Bump Project Version
description: Bumps the version of the project - defaults to bumping the release candidate number. Outputs the new version

inputs:
  rule:
    description: The version bump rule to run.
    required: false
    default: "prerelease"

outputs:
  new-project-version:
    description: The version of the current project
    value: ${{ steps.get-version.outputs.project-version }}

runs:
  using: composite
  steps:
    - name: Bump Project Version
      id: bump-version
      shell: bash
      run: poetry version ${{ inputs.rule }}

    - name: Fix Prerelease Version Format
      if: ${{ inputs.rule == 'prerelease' }}
      shell: bash
      run: poetry version $(echo "$(poetry version -s)" | sed 's/rc/-rc./g')

    - name: Get New Project Version
      id: get-version
      uses: triaxtec/github-actions/python/get-project-version@v3