name: Publish Package
description: Publishes the currently installed python package
inputs:
  token:
    description: The token used to upload the package
    required: true
  private-package-repo-url:
    description: The url of the private package repository you want to upload to (if any).
    required: false
    default: NOT_SPECIFIED
  dir:
    description: The directory containing the package to publish
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Publish Python Package
      shell: bash
      run: |
        cd ${{ inputs.dir }}
        if [[ "${{inputs.private-package-repo-url}}" != "NOT_SPECIFIED" ]]; then
          echo "Uploading to private repo (${{inputs.private-package-repo-url}})"
          poetry config repositories.private ${{ inputs.private-package-repo-url }}
          poetry config http-basic.private ${{ inputs.token }} ${{ inputs.token }}
          poetry publish --build -r private
        else
          echo "Uploading to PyPI"
          poetry config http-basic.pypi __token__ ${{ inputs.token }}
          poetry publish --build
        fi
