name: Publish Package
description: Publishes the currently installed python package
inputs:
  token:
    description: The token used to upload the package
    required: true
  private-package-repo-url:
    description: The url of the private package repository you want to upload to (if any).
    required: false
    default: NOT_SPECIFIED

runs:
  using: composite
  steps:
    - name: Publish Python Package
      shell: bash
      run: |
        if [[ "${{inputs.private-package-repo-url}}" != "NOT_SPECIFIED" ]]; then
          poetry config repositories.private ${{ inputs.private-package-repo-url }}
          poetry config http-basic.private __token__ ${{ inputs.token }}
          poetry publish --build -r private
        else
          poetry config http-basic.pypi __token__ ${{ inputs.token }}
          poetry publish --build
        fi
