name: Generate OpenAPI Document
description: Generates an OpenAPI Document from a FastAPI project

inputs:
  dependency-hash-version:
    required: false
    default: "v1"
  private-package-repo-url:
    description: The url of the private package repository you want to add to poetry. You must also specify `private-package-repo-username`
    required: false
    default: ""
  extras:
    description: Extras to include when installing this package
    required: false
    default: NOT_SPECIFIED
  working-directory:
    description: The working directory where this action should run. Defaults to the root of the git repository.
    required: false
    default: "."
  cli-name:
    description: The name of the CLI for this project
    required: true
  private-package-repo-username:
    required: false
  private-package-repo-password:
    required: false

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup python and poetry and install dependencies
      uses: triaxtec/github-actions/python/setup-python-and-poetry-and-install-dependencies@TSD-1141-add-fallback-dependency-cache-keys
      with:
        private-package-repo-url: ${{ inputs.private-package-repo-url }}
        private-package-repo-username: ${{ inputs.private-package-repo-username }}
        private-package-repo-password: ${{ inputs.private-package-repo-password }}
        dependency-hash-version: ${{ inputs.dependency-hash-version }}
        extras: ${{ inputs.extras }}
        working-directory: ${{ inputs.working-directory }}

    - name: Use test_config as config
      shell: bash
      run: mv tests/test_config.yml config.yml

    - name: Build Code
      shell: bash
      run: poetry run ${{ inputs.cli-name }} build

    - name: Generate OpenAPI Doc
      shell: bash
      run: poetry run ${{ inputs.cli-name }} openapi
