name: Rust Makefile
description: Runs the given Makefile target(s) on Rust projects

inputs:
    makefile_root:
        description: "Location of the Makefile"
        required: false
        default: '.'
    makefile_targets:
        description: "One or more make targets to run"
        required: false
        default: ''
    rustup_components:
        description: "Additional components to install via rustup"
        required: false
        default: ''
  
runs:
  using: docker
  image: Dockerfile
