name: Release Rust Binary
description: "Build and upload a release build of a Rust binary"

inputs:
  binary_name:
    description: "The name of the binary that will be built"
    required: true
  working_directory:
    description: "Working directory to run the action in. Defaults to $GITHUB_WORKSPACE"
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Set up Rust
      uses: triaxtec/github-actions/rust/setup@composite-actions
    - name: Build the binary
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release ${{ fromJSON(join(["[--manifest-path \"",inputs.working_directory,"/Cargo.toml\",\"\""],""))[inputs.working_directory == github.workspace] }}
    - name: Upload the binary
      uses: actions/upload-artifact@v2
      # The grossness with fromJSON works around the fact that conditionals are not supported
      # by implicitly indexing an array (false == 0, true == 1).
      with:
        name: ${{ inputs.binary_name }}${{ fromJSON('["",".exe"]')[runner.os == 'Windows'] }}
        path: target/release/${{ inputs.binary_name }}${{ fromJSON('["", ".exe"]')[runner.os == 'Windows'] }}
