name: Deny Check
description: Checks all dependencies for security advisories, approved licenses, bans, and approved sources.

inputs:
    check_which:
        description: "Which cargo-deny check target(s) to run: all, advisories, bans, licenses, sources"
        required: false
        default: 'all'

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libfindbin-libs-perl libssl-dev make
      shell: bash
    - name: Install cargo-deny
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-deny
        version: latest
        use-tool-cache: true
    - name: (Debug) list all files
      run: find / -name "deny.toml" -print
      shell: bash
    - name: Deny Check
      run: cargo deny check -c ./deny.toml ${{ inputs.check_which }}
      shell: bash

