name: Check Licenses
description: Checks all dependencies for approved licenses and errors if a non-approved one is found

inputs:
    check_which:
        description: "Which cargo-deny check target(s) to run: all, advisories, bans, licenses, sources"
        required: false
        default: 'all'
  
runs:
  using: docker
  image: Dockerfile
