name: Run Checks
description: Runs Triax's standard suite of checks (linting, mypy, safety, and unit tests). Assumes that any services needed for tests have been instantiated already.
inputs:
  module:
    description: The name of the module to run the checks on
    required: true


runs:
  using: composite
  steps:
    - name: Run Black
      shell: bash
      run: poetry run black . --check

    - name: Run isort
      shell: bash
      run: poetry run isort . --check

    - name: Run flake8
      shell: bash
      run: poetry run flake8 ${{ inputs.module }}

    - name: Run safety
      shell: bash
      run: poetry export -f requirements.txt | poetry run safety check --bare --stdin

    - name: Run mypy
      shell: bash
      run: poetry run mypy --show-error-codes ${{ inputs.module }}
      
    - name: Run pytest
      shell: bash
      run: poetry run pytest --cov=${{ inputs.module }} --cov-report=term-missing