name: Run Checks
description: Runs Triax's standard suite of checks (linting, mypy, safety, and unit tests). Assumes that any services needed for tests have been instantiated already.
inputs:
  module:
    description: The name of the module to run the checks on
    required: true
  test-dir:
    description: The directory (or path from the project root) containing the pytests to run. Defaults to "tests".
    required: false
    default: tests

runs:
  using: composite
  steps:
    - name: Run Black
      shell: bash
      run: poetry run black . --check

    - name: Run isort
      shell: bash
      run: poetry run isort . --check

    - name: bandit
      shell: bash
      run: poetry run bandit -r contact_tracing -s B104,B108

    - name: Lint (source)
      shell: bash
      run: poetry run task lint

    - name: Lint (tests)
      shell: bash
      run: poetry run task lint_tests

    - name: Run safety
      shell: bash
      run: poetry export -f requirements.txt | poetry run safety check --bare --stdin

    - name: Run mypy
      shell: bash
      run: poetry run mypy --show-error-codes ${{ inputs.module }}
      
    - name: Run pytest
      shell: bash
      run: poetry run pytest --cov=${{ inputs.module }} --cov-report=term-missing ${{ inputs.test-dir }}
      
    - name: Generate coverage report
      shell: bash
      run: poetry run coverage xml
