name: Release Rust Binary
description: "Checks out the code and builds and uploads a release build of a Rust binary"

inputs:
  binary_name:
    description: "The name of the binary that will be built"
    required: true
  working_directory:
    description: "Working directory to run the action in. Defaults to $GITHUB_WORKSPACE"
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: triaxtec/github-actions/rust/actions/setup@TSD-274-reusable-workflows

    - name: Build and Upload Binary
      uses: triaxtec/github-actions/rust/actions/build-and-upload@TSD-274-reusable-workflows
      with:
        binary_name: ${{ inputs.binary_name }}
        working_directory: ${{ inputs.working_directory }}
