name: Run Rust lints
description: Runs clippy and rustfmt lints

inputs:
  github_token:
    description: "GitHub token, i.e. secrets.GITHUB_TOKEN. Is passed to the clippy check to annotate pull requests"
    required: true
  clippy_args:
    description: "Any extra arguments to pass to clippy."
    required: false
    default: "--all-features"
  working_directory:
    description: "Working directory to run the action in. Defaults to $GITHUB_WORKSPACE"
    required: false
    default: NOT_SPECIFIED

runs:
  using: composite
  steps:
    - name: Test
      run: echo ${{ inputs.working_directory }}
      shell: bash

    - name: Run clippy lints
      if: ${{ inputs.working_directory == 'NOT_SPECIFIED'}}
      with:
        token: ${{ inputs.github_token }}
        args:  ${{ inputs.clippy_args }}

    - name: Run clippy lints
      if: ${{ inputs.working_directory != 'NOT_SPECIFIED'}}
      with:
        token: ${{ inputs.github_token }}
        args: --manifest-path ${{inputs.working_directory}}/Cargo.toml ${{ inputs.clippy_args }}
    
    - name: Run rustfmt check
      if: ${{ inputs.working_directory == 'NOT_SPECIFIED'}}
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --manifest-path ${{inputs.working_directory}}/Cargo.toml  -- --check

    - name: Run rustfmt check
      if: ${{ inputs.working_directory != 'NOT_SPECIFIED'}}
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check