name: Deploy

on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      cli-name:
        required: false
        type: string
      working-directory:
        required: false
        type: string
        default: "."
      dependency-hash-version:
        required: false
        type: string
        default: "v1"
      private-package-repo-url:
        description: The url of the private package repository you want to add to poetry. You must also specify `private-package-repo-username`
        type: string
        required: false
        default: ""
      aws-default-region:
        type: string
        required: false
        default: "us-east-1"
    secrets:
      private-package-repo-username:
        required: false
      private-package-repo-password:
        required: false
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build-and-deploy:
    name: Deploy to ${{ inputs.environment }}
    
    runs-on: ubuntu-latest
    container: amazon/aws-lambda-python:3.8

    steps:
      - name: Install tar and gzip
        run: yum install -y tar gzip
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies with Poetry
        uses: triaxtec/github-actions/python/install-dependencies-with-poetry@update-poetry
        with:
          private-package-repo-url: ${{inputs.private-package-repo-url}}
          private-package-repo-username: ${{secrets.private-package-repo-username}}
          private-package-repo-password: ${{secrets.private-package-repo-password}}
          working-directory: ${{inputs.working-directory}}
          dependency-hash-version: ${{inputs.dependency-hash-version}}

      - name: Build Code
        working-directory: ${{ inputs.working-directory }}
        if: ${{ inputs.cli-name != '' }}
        run: poetry run ${{ inputs.cli-name }} build

      - name: Generate Requirements
        working-directory: ${{ inputs.working-directory }}
        run: poetry export -f requirements.txt -o requirements.txt --with-credentials --without-hashes

      - name: Serverless Deploy to ${{ inputs.environment }}
        uses: triaxtec/github-actions/generic/serverless-deploy@v2
        with:
          environment: ${{ inputs.environment }}
          aws-default-region: ${{ inputs.aws-default-region }}
          working-directory: ${{ inputs.working-directory }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
