name: Publish Python Package

on:
  workflow_call:
    inputs:
      dependency-hash-version:
        required: false
        type: string
        default: "v1"
      private-package-repo-url:
        description: The url of the private package repository you want to add to poetry. You must also specify `private-package-repo-username`
        required: false
        type: string
        default: ""
      extras:
        description: Extras to include when installing this package
        type: string
        required: false
        default: NOT_SPECIFIED
      working-directory:
        description: The working directory where this action should run. Defaults to the root of the git repository.
        type: string
        required: false
        default: "."
    secrets:
      private-package-repo-username:
        required: false
      private-package-repo-push-token:
        required: false

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python and Poetry and Install Dependencies
      uses: triaxtec/github-actions/python/setup-python-and-poetry-and-install-dependencies@update-poetry
      with:
        private-package-repo-url: ${{ inputs.private-package-repo-url }}
        private-package-repo-username: ${{ secrets.private-package-repo-username }}
        dependency-hash-version: ${{ inputs.dependency-hash-version }}
        exclude-dev-dependencies: true
        extras: ${{ inputs.extras }}

    - name: Build and Publish
      uses: triaxtec/github-actions/python/publish-package@v2
      with:
        private-package-repo-url: ${{ inputs.private-package-repo-url }}
        token: ${{ secrets.private-package-repo-push-token }}
        dir: ${{ inputs.working-directory }}