name: Bump Version and Tag

on: 
  workflow_call

jobs:
  bump-version-and-commit:
    name: Bump Project Version, Commit, and Tag
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install and Configure Poetry
        uses: triaxtec/github-actions/python/install-and-configure-poetry@v3
        with:
          poetry-version:  1.4.1
          working-directory: ${{inputs.working-directory}}

      - name: Bump Project Version
        id: bump-version
        uses: triaxtec/github-actions/python/bump-project-version@v3

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Bump version to v.${{ steps.bump-version.outputs.new-project-version }}"
          tagging_message: v.${{ steps.bump-version.outputs.new-project-version }}
