name: Build Binaries and Upload them as Artifacts

on:
  workflow_call:
    secrets:
      ssh-private-key:
        description: "SSH key used to pull private dependencies from GitHub"
        required: true

jobs:
    build-and-upload:
      strategy:
        matrix:
          os: [ windows-latest, ubuntu-latest, macos-latest ]
      name: Build Binary for ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Add SSH key so cargo can access private repos
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.ssh-private-key }}

        - name: Setup Rust and Install Dependencies
          uses: triaxtec/github-actions/rust/setup@v3
        
        - name: Build and Upload
          uses: triaxtec/github-actions/rust/build-and-upload@v3
          with:
            binary_name: eat